version: "3.5"

networks: 
  proxy-ntw:
    name: spring_mysql_ntw

services: 
  api: 
    image: amarnath510/spring-boot-mysql-app
    networks: 
      - proxy-ntw
    container_name: company-api
    ports: 
      - 8200:8200
    depends_on: 
      - db
    restart: on-failure # Will fail first time since mysql is not up. So if it fails then it tries to restart app again
                        # More options https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy

  db: 
    image: amarnath510/mysql-5.6-docker-image
    networks: 
      - proxy-ntw
    container_name: database # This name is used in spring-boot application.yml for mysql url.
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: company
