version: "3.5"

networks: 
  proxy-ntw:
    name: spring_mysql_ntw

services: 
  companyApi:  # Service name
    image: amarnath510/spring-boot-mysql-app
    networks: 
      - proxy-ntw
    ports: 
      - 8200:8200
    depends_on: 
      - database
    restart: on-failure # Will fail first time since mysql is not up. So if it fails then it tries to restart app again
                        # More options https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy
                        # 'restart' is not needed when running via Swarm because it automatically restarts services if failed

  database:   # Service name. This is mentioned in spring-app's application.yml file mysql url(jdbc:mysql://database:3306/company)
              # So don't mess with the names. If you rename here then you need to renamed in yml file and rebuild the jar
    image: amarnath510/mysql-5.6-docker-image
    networks: 
      - proxy-ntw
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: company
